server:
  port: 8901

spring:
  application:
    name: client-feign-zyf

eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8848/eureka
feign:
  hystrix:
    #开启断路器
    enabled: true